<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends Admin_Controller{
    function __construct()
    {
        parent::__construct(); 
         
    }

    function index()
    {
        $this->load->model('Admin_model');
        $data['total_admin'] = $this->Admin_model->get_all_admin_count();



        $this->load->model('Item_model');
        $data['cliennt_count'] = $this->Item_model->get_sum_profit_count();

                $data['total_price'] = $this->Item_model->get_sum_total_price();

            
                 $data['product_price'] = $this->Item_model->price_of_product();

                 $data['customer_name'] = $this->Item_model->customer_name();
                 //print_r($data['customer_name']);exit();
                   $data['customer_products'] = $this->Item_model->customer_products();
                  

        $data['total_item'] = $this->Item_model->get_all_items_count();



        $this->load->model('Purchase_model');
        $data['total_customers'] = $this->Purchase_model->get_all_customers_count();

        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
