<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Order_items extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Orders_model');
    } 

    /*
     * Listing of customers
     */
    function index()
    {

        $data['orders_items'] = $this->Orders_model->get_all_Order_items();
      // echo "<pre>"; print_r($data['orders']);exit();
          

          

        
        $data['_view'] = 'orders_items/index';
        $this->load->view('layouts/main',$data);
    }

    function remove($id)
    {
        $order_item = $this->Orders_model->get_order_items($id);

        // check if the admin exists before trying to delete it
        if(isset($order_item['id']))
        {
            $this->Orders_model->delete_order_items($id);
            redirect('Order_items/index');
        }
        else
            show_error('The Product you are trying to delete does not exist.');
    }
}