<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itemused_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get itemused by id
     */
    function get_itemused($id)
    {
        return $this->db->get_where('items',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all itemused count
     */
    function get_all_itemused_count()
    {
        $this->db->from('items');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all itemused
     */
    function get_all_itemused($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
              $this->db->where('items.delete_id=1');
        return $this->db->get('items')->result_array();

    }
        
    /*
     * function to add new itemused
     */
    function add_itemused($params)
    {
        $this->db->insert('items',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update itemused
     */
    function update_itemused($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('items',$params);
    }
    
    /*
     * function to delete itemused
     */
    function delete_itemused($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('items',$params);
//        return $this->db->delete('itemused',array('id'=>$id));
    }
    /*
    * function to insert delete Record
    */
    function insert_deleterec($params)
    {
        return $this->db->insert('deleterec',$params);

    }
}
