<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Purchase_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get customers by id
     */
    function get_customers($id)
    {
        
        return $this->db->get_where('customers',array('id'=>$id))->row_array();
    }

    
  
    
    /*
     * Get all customers count
     */
    function get_all_customers_count()
    {
        $this->db->from('customers');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all customers
     */
    function get_all_customers($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
       
        $this->db->where('customers.delete_id=1');
       return $this->db->get('customers')->result_array();
    }
        
    /*
     * function to add new customers
     */
    function add_customers($params)
    {


        $this->db->insert('customers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customers
     */
    function update_customers($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('customers',$params);
    }
    
    /*
     * function to delete customers
     */
    function delete_customers($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('customers',$params);
//        return $this->db->delete('customers',array('id'=>$id));
    }
    /*
    * function to insert delete Record
    */
    function insert_deleterec($params)
    {
        return $this->db->insert('deleterec',$params);

    }
}
